FROM node:latest
WORKDIR /usr/webapp/src
COPY package.json .
COPY src src/.
COPY public public/.
RUN npm install --silent
RUN npm run-script build
COPY build build/.
EXPOSE 3000
CMD [ "npm", "start" ]
