version: '3.7'

services:
    
    mongo:
        image: mongo
        container_name: mongodb
        ports:
          - 27017:27017
        networks:
          - closed

    api:
        build:
          context: ./backend
          dockerfile: dockerfile
        ports: 
          - 3001:3001
        environment:
          - MONGO_PATH='mongodb://mongo:27017/depmapper'
        networks:
          - closed
          - public
        depends_on:
          - mongo
    
    app:
        build:
          context: ./frontend
          dockerfile: dockerfile
        ports: 
          - 3000:3000
        networks:
          - public
    nginx:
        image: nginx:latest 
        networks:
          - public
          - closed
        ports:
          - 8080:80
          - 8443:443
        volumes:
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
          - ./:/usr/webapp/src
          - ./proxy/nginx.conf:/etc/nginx/nginx.conf  
        depends_on:
          - app
          - api
    certbot:
        image: certbot/certbot
        volumes:
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
 
networks:
    closed:
    public:   
       
 