version: '3.7'

services:
    mongo:
        image: mongo
        ports:
          - 27017:27017

    api:
        build:
          context: ./backend
          dockerfile: dockerfile
        ports: 
          - 3001:3001
        depends_on:
          - mongo
    
    app:
        build:
          context: ./frontend
          dockerfile: dockerfile
        ports: 
          - 3000:3000
        depends_on:
          - mongo