version: '3.7'

services: 

    mongo:
      image: mongo
      networks:
        - closed

    api:
      build:
        context: ./backend
        dockerfile: dockerfile
      ports:
        - 3001:3001
      environment:
        - MONGO_PATH='mongodb://mongo:27017/depmapper'
      networks:
        - public
        - closed
      depends_on:
        - mongo

    build-web:
      build:
        context: ./frontend
        dockerfile: dockerfile-dist
      command: npm run build
      volumes:
        - static-webapp:/usr/webapp/src/build

    nginx:
      image: nginx:latest 
      networks:
        - public
        - closed
      ports:
        - 8080:80
        - 8443:443
      volumes:
        - static-webapp/:/www/webapp/
        - ./proxy/nginx.conf:/etc/nginx/nginx.conf  
      depends_on:
        - build-web
        - api
 
networks:
    closed:
    public:   
       