version: '3.7'

services:
    
    mongo:
        image: mongo
        container_name: mongodb
        ports:
          - 27017:27017
        networks:
          - closed

    api:
        build:
          context: ./backend
          dockerfile: dockerfile
        ports: 
          - 3001:3001
        environment:
          - MONGO_PATH='mongodb://mongo:27017/depmapper'
        networks:
          - closed
          - public
        depends_on:
          - mongo
    
    app:
        build:
          context: ./frontend
          dockerfile: dockerfile
        ports: 
          - 3000:3000
        networks:
          - public
networks:
    closed:
    public:   
       
 