FROM nginx:latest


RUN apt update
RUN apt-get install openssl apache2-utils -y
RUN apt-get install certbot python-certbot-nginx -y

COPY nginx.conf etc/nxing/.
COPY certs /etc/nginx/certs/.
COPY data/renewal/gwiki.cs-aware.eu.conf etc/letsencrypt/renewalbroken/gwiki.cs-aware.eu.conf/.
COPY certs/privkey.pem /etc/letsencrypt/live/gwiki.cs-aware.eu/privkey.pem/.
COPY certs/fullchain.pem /etc/letsencrypt/live/gwiki.cs-aware.eu/fullchain.pem/.

COPY test etc/nginx/test/test/.
COPY acmechallenge etc/nginx/html/.well-known/. 
RUN certbot renew


