FROM nginx:latest


RUN apt update
RUN apt-get install openssl apache2-utils -y
RUN apt-get install certbot python-certbot-nginx -y

COPY nginx.conf etc/nxing/.
COPY certs /etc/nginx/certs/.
COPY data etc/letsencrypt



COPY test etc/nginx/test/test/.
COPY acmechallenge etc/nginx/html/.well-known/. 
 


