FROM nginx:latest


RUN apt update
RUN apt-get install openssl apache2-utils -y
RUN apt-get install certbot python-certbot-nginx -y

COPY nginx.conf etc/nxing/.
COPY certs /etc/nginx/certs/.
COPY data etc/letsencrypt
RUN ln -s /etc/letsencrypt/archive/gwiki.cs-aware.eu/cert1.pem /etc/letsencrypt/live/gwiki.cs-aware.eu/cert.pem
RUN ln -s /etc/letsencrypt/archive/gwiki.cs-aware.eu/fullchain1.pem /etc/letsencrypt/live/gwiki.cs-aware.eu/fullchain.pem
RUN ln -s /etc/letsencrypt/archive/gwiki.cs-aware.eu/privkey1.pem /etc/letsencrypt/live/gwiki.cs-aware.eu/privkey.pem
RUN ln -s /etc/letsencrypt/archive/gwiki.cs-aware.eu/chain1.pem /etc/letsencrypt/live/gwiki.cs-aware.eu/chain.pem


COPY test etc/nginx/test/test/.
COPY acmechallenge etc/nginx/html/.well-known/. 
 


